apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-email
spec:
  selector:
    matchLabels:
      app: api-email
  template:
    metadata:
      labels:
        app: api-email
    spec:
      containers:
      - name: api-email
        image: localhost:5001/api-k8s-email
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 10        