apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-pessoa
spec:
  selector:
    matchLabels:
      app: api-pessoa
  template:
    metadata:
      labels:
        app: api-pessoa
    spec:
      containers:
      - name: api-pessoa
        image: localhost:5001/api-k8s-pessoa
        imagePullPolicy: Always
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"        
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
            scheme: HTTP
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 10
          successThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 20          
        envFrom:
          - configMapRef:
              name: mysql
          - secretRef:
              name: mysql
