apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-idade-email
spec:
  selector:
    matchLabels:
      app: api-idade-email
  template:
    metadata:
      labels:
        app: api-idade-email
    spec:
      containers:
      - name: api-idade-email
        image: localhost:5001/api-k8s-idade-email
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
            scheme: HTTP
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 10          
          successThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 20          